# Site settings
title: Rankeezy style guide
email: www.rankeezy.com
description: A style guide for Rankeezy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rankeezy.github.io" # the base hostname & protocol for your site

# Colletions
collections: 
  - components

# Build settings
markdown: kramdown
