# Site settings
title: Rankeezy Styleguide
email: www.rankeezy.com
description: A Styleguide for Rankeezy
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site

# Colletions
collections: 
  - components

# Build settings
markdown: kramdown